### PR TITLE
Create docs folder in main

### PR DESCRIPTION
**Pull request by Evorage0**

### CODE REVIEW

**Review by dawnofmidnight — CHANGES_REQUESTED** [review]
This should be a markdown file in /docs/backend. Preferably with a name like api.md

**Comment by dawnofmidnight** [comment]
Or a yaml file would be fine if it's an api spec

cc @doublevcodes

**Comment by dawnofmidnight** [comment]
Or a yaml file would be fine if it's an api spec

cc @doublevcodes

**Comment by doublevcodes** [comment]
**`openapi.yaml`**

**Comment by dawnofmidnight** [comment]
Let's keep this as a draft until it's actually documented, we don't need a pr just to create an empty file

**Comment by dawnofmidnight** [comment]
Superseded by #88

**Pull request closed without merging**
