### PR TITLE
Refactor logger.py: see extended desc

### PR DESCRIPTION
**Pull request by Objectivitix**
1. remove redundancy
2. refine type annotations
3. add logical spacing
4. collapsed normal logs all into one func

### CODE REVIEW

**Review by Kronifer — CHANGES_REQUESTED** [review]
The lint fails, fix it before merge please(ik most of it is my fault)

**Comment by Objectivitix** [comment]
@Kronifer most of the lint errors are from other files. I'm only working on this one.

**Review by AbooMinister25 — APPROVED** [review]
Alright, this looks good, I think we should PR.

**Review by Kronifer — APPROVED** [review]
Approved, but please fix the linting, if you do you get chad guy points

**Review by dawnofmidnight — DISMISSED** [review]
Let's wait until linting has been fixed, it's becoming a problem

**Comment by Objectivitix** [comment]
Lint fails are from other files which is NOT the purpose of this PR... sure, I can fix a few bare excepts, but that would make this PR messy, and it's bad practice

Also, don't merge this yet, I'm drafting, gotta refactor some more stuff

**Comment by dawnofmidnight** [comment]
> @Kronifer @dawnofmidnight Lint fails are from other files which is NOT the purpose of this PR... sure, I can fix a few bare excepts, but that would make this PR messy, and it's bad practice

Someone could open a PR to fix that then

**Comment by Objectivitix** [comment]
@Kronifer @dawnofmidnight There have been new changes, please re-review.

**Review by AbooMinister25 — APPROVED** [review]
Alright, so all of this looks good, I can fix the linting problems in another PR, as well as refactor the rest of the files so that it'll follow the revamped logger.

**Pull request merged**
