### PR TITLE
Added snowflake generation, init.sql and another sql task

### PR DESCRIPTION
**Pull request by Kronifer**
Literally the title, added init.sql to the docker-compose file, etc.

### CODE REVIEW

**Review by AbooMinister25 — APPROVED** [review]
This looks good, it passes all checks, and the files look fine.

**Review by AbooMinister25 — CHANGES_REQUESTED** [review]
Kronifer, I why are you adding `init.sql` as a volume?

**Comment by AbooMinister25** [comment]
`init.sql` shouldn't be added as a volume

**Review by AbooMinister25 — CHANGES_REQUESTED** [review]
What you should be doing is creating the database by executing init.sql *once*, and then executing it. I've made this function you can put in your `tasks.py`
```py
async def initialize_db():
    conn = await get_db()

    logger.info("Attempting to open init.sql file")

    try:
        async with aiofiles.open("backend/init.sql", mode="r") as f:
            sql = await f.read()
        logger.info("Successfully opened init.sql file")
    except Exception as e:
        logger.error("Exception occured while attempting to open init.sql file")
        logger.error(e)
        return

    logger.info("Attempting to execute sql")

    try:
        await conn.execute(sql)
        logger.success("Successfully executing SQL")
    except Exception as e:
        logger.error("Exception occured while executing sql")
        logger.error(e)
    finally:
        logger.info("Closing database")
        await conn.close()
```
Execute this once, don't add init.sql as a volume. The data should automatically persist, I've tested it

**Review by Evorage0 — CHANGES_REQUESTED** [review]
```py
import time

token_counter = 0
def gensnowflake():
    milliseconds_since_epoch = time.time_ns() // 1000000
    snowflake = milliseconds_since_epoch << 8 + token_counter
    token_counter +=1
    if token_counter == 256: token_counter = 0
    return snowflake
```

**Comment by Kronifer** [comment]
@AbooMinister25 it is only executed on the volume creation, which is when the image is completely reser

**Comment by Kronifer** [comment]
Reset

**Comment by AbooMinister25** [comment]
> @AbooMinister25 it is only executed on the volume creation, which is when the image is completely reset

Ah ok, thats good then

**Review by AbooMinister25 — APPROVED** [review]
Alright, everything seems good then, we can merge this PR.

**Pull request merged**
