### PR TITLE
Restructured backend of API.

### PR DESCRIPTION
**Pull request by AbooMinister25**
Moved all API code from `__main__.py` to `routes/` folder and sorted them based on their respective tasks. Moved pydantic schemas to a separate `schemas.py` file.

### CODE REVIEW

**Comment by dawnofmidnight** [comment]
I prefer endpoints/ over routes/ since they're commonly known as API endpoints

**Comment by Kronifer** [comment]
agreed

**Review by Kronifer — CHANGES_REQUESTED** [review]
Don't really have a problem, but please correct config.py

**Comment by AbooMinister25** [comment]
> I prefer endpoints/ over routes/ since they're commonly known as API endpoints
Alright, i can fix that

**Review by Kronifer — CHANGES_REQUESTED** [review]
please get rid of your .idea files

**Comment by doublevcodes** [comment]
```zsh
git rm --cached -r -- .idea/
```
FYI

**Comment by AbooMinister25** [comment]
> please get rid of your .idea files

ok

**Review by Kronifer — APPROVED** [review]
lgtm

**Pull request merged**
